server:
    port: ${PORT:8083}

spring:
    application:
        name: interview-service

    datasource:
        url: ${INTERVIEW_DATABASE_URL:jdbc:postgresql://localhost:5432/interview_db}
        username: ${INTERVIEW_DATABASE_USERNAME:lalit}
        password: ${INTERVIEW_DATABASE_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: ${JPA_DDL_AUTO:update}
        show-sql: ${JPA_SHOW_SQL:false}
jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}
