server:
    port: ${PORT:8084}

spring:
    application:
        name: attempt-service

    datasource:
        url: ${ATTEMPT_DATABASE_URL:jdbc:postgresql://localhost:5432/attempt_db}
        username: ${ATTEMPT_DATABASE_USERNAME:lalit}
        password: ${ATTEMPT_DATABASE_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: ${JPA_DDL_AUTO:update}
        show-sql: ${JPA_SHOW_SQL:false}
jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION:86400000}

services:
    interview:
        url: ${INTERVIEW_SERVICE_URL:http://localhost:8083}

    judge:
        url: ${JUDGE_SERVICE_URL:http://localhost:8085}

    ai:
        url: ${AI_SERVICE_URL:http://localhost:8086}
